version: '3.8'

services:
  db:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: example
      POSTGRES_DB: e2e-test
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    build: .
    container_name: portfolio-api
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://tester:example@db:5432/e2e-test
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run test:e2e

