version: '3.8'

services:
  db:
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
    build: .
    container_name: portfolio-api
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: mongodb://root:example@db:27017
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run test:e2e

